In [15]:
import numpy as np
import pandas as pd

In [2]:
# Define the number of rows for synthetic data (10 million)
num_rows = 10_000_000

In [16]:
# Generate synthetic data based on the structure of Sheet2
num_rows = 5000000

def generate_synthetic_data(txn_flow,min_product_id=10,max_product_id=110,num_rows = 5000000):
    
    synthetic_data = pd.DataFrame({
        "account_id": np.random.randint(1000000, 2000000, num_rows),
        "product_id": np.random.randint(min_product_id, max_product_id, num_rows),
        "txn_amt": np.random.uniform(10, 1000, num_rows).round(2),
        # "txn_flow": np.random.choice(["credit", "debit","valuechain"], num_rows),
        "date_id": np.random.randint(6000, 6730, num_rows),
    })
    synthetic_data["txn_flow"] = txn_flow
    return synthetic_data

In [18]:
debit = generate_synthetic_data("debit",min_product_id=10,max_product_id=110,num_rows = 5000000)

In [19]:
credit = generate_synthetic_data("credit",min_product_id=10,max_product_id=110,num_rows = 3000000)

In [20]:
service = generate_synthetic_data("services",min_product_id=111,max_product_id=211,num_rows = 2000000)

In [21]:
all_df = pd.concat([debit,credit,service])
all_df

         account_id  product_id  txn_amt  date_id  txn_flow
0           1675009          14   395.39     6172     debit
1           1006123          28   409.89     6181     debit
2           1936846          74    56.50     6450     debit
3           1542862         104    43.09     6370     debit
4           1648106          97   849.56     6154     debit
...             ...         ...      ...      ...       ...
1999995     1735220         169   877.41     6280  services
1999996     1043980         123   777.06     6610  services
1999997     1711453         120   695.65     6006  services
1999998     1675860         139   596.84     6266  services
1999999     1193376         134   739.56     6698  services

[10000000 rows x 5 columns]

In [22]:
all_df['account_id'].nunique()

999958

In [23]:
all_df.drop_duplicates(subset=["account_id","product_id","date_id","txn_flow"])

         account_id  product_id  txn_amt  date_id  txn_flow
0           1675009          14   395.39     6172     debit
1           1006123          28   409.89     6181     debit
2           1936846          74    56.50     6450     debit
3           1542862         104    43.09     6370     debit
4           1648106          97   849.56     6154     debit
...             ...         ...      ...      ...       ...
1999995     1735220         169   877.41     6280  services
1999996     1043980         123   777.06     6610  services
1999997     1711453         120   695.65     6006  services
1999998     1675860         139   596.84     6266  services
1999999     1193376         134   739.56     6698  services

[9999735 rows x 5 columns]

In [24]:
debit2 = generate_synthetic_data("debit",min_product_id=10,max_product_id=110,num_rows = 265)

In [25]:
all_df = pd.concat([all_df,debit2])
all_df

     account_id  product_id  txn_amt  date_id txn_flow
0       1675009          14   395.39     6172    debit
1       1006123          28   409.89     6181    debit
2       1936846          74    56.50     6450    debit
3       1542862         104    43.09     6370    debit
4       1648106          97   849.56     6154    debit
..          ...         ...      ...      ...      ...
260     1102857          21   281.49     6617    debit
261     1899285          86   799.01     6195    debit
262     1807224          65   121.67     6179    debit
263     1046974          96   143.07     6055    debit
264     1348527         104   931.36     6535    debit

[10000265 rows x 5 columns]

In [27]:
all_df.drop_duplicates(subset=["account_id","product_id","date_id","txn_flow"],inplace=True)

In [28]:
# Save the synthetic data to a CSV file
synthetic_file_path = "synthetic_customer_churn_data.csv"
all_df.to_csv(synthetic_file_path, index=False,)

synthetic_file_path

'synthetic_customer_churn_data.csv'